CREATE DATABASE PCSERV;

CREATE TABLE KLIENT (
  ID_Klient INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Imie VARCHAR(20) NULL,
  Nazwisko VARCHAR(25) NULL,
  Telefon VARCHAR(12) NULL,
  Email VARCHAR(45) NULL,
  PRIMARY KEY(ID_Klient)
);

CREATE TABLE UZYTKOWNIK (
  ID_Uzytkownik INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Email VARCHAR(30) NOT NULL UNIQUE,
  Haslo VARCHAR(256) NOT NULL,
  Rola VARCHAR(10) NULL,
  PRIMARY KEY(ID_Uzytkownik)
);

CREATE TABLE PRACOWNIK (
  ID_Pracownik INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Imie VARCHAR(20) NULL,
  Nazwisko VARCHAR(25) NULL,
  Telefon VARCHAR(12) NULL,
  PRIMARY KEY(ID_Pracownik)
);

CREATE TABLE RODZAJ (
  ID_Rodzaj INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nazwa VARCHAR(25) NULL,
  PRIMARY KEY(ID_Rodzaj)
);

CREATE TABLE SPRZET (
  ID_Sprzet INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  RODZAJ_ID_Rodzaj INTEGER UNSIGNED NOT NULL,
  SerialNumber VARCHAR(25) NULL,
  Producent VARCHAR(20),
  PRIMARY KEY(ID_Sprzet),
  INDEX SPRZET_FKIndex1(RODZAJ_ID_Rodzaj)
);

CREATE TABLE STATUS_Z (
  ID_Status INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nazwa VARCHAR(25) NULL,
  PRIMARY KEY(ID_Status)
);

CREATE TABLE ZGLOSZENIE (
  ID_Zgloszenie INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  SPRZET_ID_Sprzet INTEGER UNSIGNED NOT NULL,
  KLIENT_ID_Klient INTEGER UNSIGNED NOT NULL,
  STATUS_Z_ID_Status INTEGER UNSIGNED NOT NULL,
  PRACOWNIK_ID_Pracownik_Przyjmujacy INTEGER UNSIGNED NOT NULL,
  PRACOWNIK_ID_Pracownik_Wydajacy INTEGER UNSIGNED,
  Data_Przyjecia DATE,
  Data_Wydania DATE,
  Opis VARCHAR(255) NULL,
  PRIMARY KEY(ID_Zgloszenie),
  INDEX ZGLOSZENIE_FKIndex1(STATUS_Z_ID_Status),
  INDEX ZGLOSZENIE_FKIndex2(KLIENT_ID_Klient),
  INDEX ZGLOSZENIE_FKIndex3(SPRZET_ID_Sprzet),
  INDEX ZGLOSZENIE_FKIndex4(PRACOWNIK_ID_Pracownik_Przyjmujacy),
  INDEX ZGLOSZENIE_FKIndex5(PRACOWNIK_ID_Pracownik_Wydajacy)
);


