CREATE TABLE KLIENT (
  ID_Klient INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Imie VARCHAR NULL,
  Nazwisko VARCHAR NULL,
  Telefon VARCHAR(12) NULL,
  Email VARCHAR(45) NULL,
  PRIMARY KEY(ID_Klient)
);

CREATE TABLE PRACOWNIK (
  ID_Pracownik INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Imie VARCHAR NULL,
  Nazwisko VARCHAR NULL,
  Telefon VARCHAR(12) NULL,
  PRIMARY KEY(ID_Pracownik)
);

CREATE TABLE RODZAJ (
  ID_Rodzaj INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nazwa VARCHAR NULL,
  PRIMARY KEY(ID_Rodzaj)
);

CREATE TABLE SPRZET (
  ID_Sprzet INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  RODZAJ_ID_Rodzaj INTEGER UNSIGNED NOT NULL,
  SerialNumber VARCHAR NULL,
  PRIMARY KEY(ID_Sprzet),
  INDEX SPRZET_FKIndex1(RODZAJ_ID_Rodzaj)
);

CREATE TABLE STATUS_Z (
  ID_Status INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nazwa VARCHAR NULL,
  PRIMARY KEY(ID_Status)
);

CREATE TABLE ZG£OSZENIE (
  ID_Zg³oszenie INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PRACOWNIK_ID_Pracownik INTEGER UNSIGNED NOT NULL,
  SPRZET_ID_Sprzet INTEGER UNSIGNED NOT NULL,
  KLIENT_ID_Klient INTEGER UNSIGNED NOT NULL,
  STATUS_Z_ID_Status INTEGER UNSIGNED NOT NULL,
  Opis VARCHAR NULL,
  PRIMARY KEY(ID_Zg³oszenie),
  INDEX ZG£OSZENIE_FKIndex1(STATUS_Z_ID_Status),
  INDEX ZG£OSZENIE_FKIndex2(KLIENT_ID_Klient),
  INDEX ZG£OSZENIE_FKIndex3(SPRZET_ID_Sprzet),
  INDEX ZG£OSZENIE_FKIndex4(PRACOWNIK_ID_Pracownik),
  INDEX ZG£OSZENIE_FKIndex5(PRACOWNIK_ID_Pracownik)
);


